---
- name: installing httpd
  dnf:
    name: httpd
    state: latest

- name: start the httpd service
  service:
    name: httpd
    state: started
    enabled: yes

- name: start firewalld service
  service:
    name: firewalld
    state: started
    enabled: yes

- name: allow access to web server
  firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled

- name: create template 
  template:
    src: index.html.j2
    dest: /var/www/html/index.html


