---
- name: user creation
  hosts: all
  become: yes
  vars_files:
    - users_list.yml
    - locker.yml
  tasks:
    - name: creating groups
      group:
        name: "{{ item }}"
        state: present
      loop:
        - devops
        - opsmgr

    - name: creating on dev and test
      user:
        name: "{{ item.name }}"
        groups: devops
        password: "{{ PW_developer | password_hash('sha512') }}"
      loop: "{{ users }}"
      when: inventory_hostname in groups['dev'] and item.job == 'developer'    

    - name: creating on prod
      user:
        name: "{{ item.name }}"
        groups: opsmgr
        password: "{{ PW_manager | password_hash('sha512') }}"
      loop: "{{ users }}"
      when: inventory_hostname in groups['prod'] and item.job == 'manager'



