---
- name: create web content directory
  hosts: dev
  become: yes
  tasks:
    - name: creating the group webdev
      group:
        name: webdev
        state: present

    - name: create webdev directory
      file:
        path: /webdev
        state: directory
        group: webdev
        setype: httpd_sys_content_t
        mode: '2775'

    - name: create symbolynk link 
      file:
        src: /webdev
        dest: /var/www/html/webdev
        state: link

    - name: create index file with Development content
      copy:
        content: "Development"
        dest: /webdev/index.html
        setype: httpd_sys_content_t




