---
- name: configure repo for all hosts
  hosts: all
  become: yes
  tasks:
    - yum_repository:
        name: EX294_BASE
        description: EX294 base software
        baseurl: http://content.example.com/rhel8.0/x86_64/dvd/BaseOS/
        gpgcheck: yes
        gpgkey: http://content.example.com/rhel8.0/x86_64/dvd/RPM-GPG-KEY-redhat-release 
        enabled: yes

    - yum_repository:
        name: EX294_STREAM
        description: EX294 stream software
        baseurl: http://content.example.com/rhel8.0/x86_64/dvd/AppStream/
        gpgcheck: yes
        gpgkey: http://content.example.com/rhel8.0/x86_64/dvd/RPM-GPG-KEY-redhat-release
        enabled: yes
